[package]
name = "silicon-apps-client"
version = "0.1.3"
edition.workspace = true
license.workspace = true
description = "Stateless primary Silicon Apps API, authentication and local installation library"
repository.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
dirs.workspace = true
fs2.workspace = true
reqwest.workspace = true
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde.workspace = true
serde_json.workspace = true
silicon-accounts-client.workspace = true
silicon-apps-package.workspace = true
space-station.workspace = true
tempfile.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
axum.workspace = true
