[package]
name = "silicon-apps-cli"
version = "0.2.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Create, publish, discover and install Silicon Apps"

[[bin]]
name = "silicon-apps"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
silicon-apps-client.workspace = true
tokio.workspace = true

[dev-dependencies]
axum.workspace = true
silicon-apps-server = { path = "../server" }
tempfile.workspace = true
