#!/usr/bin/env node
/**
 * Bundles the Carbon's hand-written agent file at build time, as the account site does (web/lib/agent/build-llms.ts):
 * store/llms/llms.md, served exactly as written at both /llms.txt and /llms-full.txt, into
 * lib/agent/generated/llms.ts, with when it last changed (git, or the file's time while it has changes of its own).
 * Nothing reads store/llms/ at run time. Never edit the .md file from code.
 *
 *   node scripts/build-llms.mjs            write the module (pnpm dev, build and typecheck run it first)
 *   node scripts/build-llms.mjs --check    fail when the module is out of date
 *   node scripts/build-llms.mjs --quiet    no output unless something is wrong
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, renameSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const llmsDir = join(root, "llms");
const output = join(root, "lib", "agent", "generated", "llms.ts");

function git(args) {
  try {
    return execFileSync("git", args, { cwd: llmsDir, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
  } catch {
    return null;
  }
}

/** When each file last changed: its last commit, or its own time while it has uncommitted changes or none at all. */
function modified(name) {
  const path = join(llmsDir, name);
  if (!existsSync(path)) return null;
  const dirty = (git(["status", "--porcelain", "--", name]) ?? "").trim() !== "";
  const committed = dirty ? "" : (git(["log", "-1", "--format=%cI", "--", name]) ?? "").trim();
  return committed ? new Date(committed).toISOString() : statSync(path).mtime.toISOString();
}

function read(name) {
  const path = join(llmsDir, name);
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

function llmsModule() {
  return [
    "/* Generated by scripts/build-llms.mjs from store/llms/llms.md: do not edit. Run `pnpm build:llms` (pnpm dev, build and typecheck do). */",
    "",
    "/** store/llms/llms.md exactly as written, served at /llms.txt and /llms-full.txt (null: the file is missing). */",
    `export const LLMS_TXT: string | null = ${JSON.stringify(read("llms.md"))};`,
    `export const LLMS_TXT_MODIFIED: string | null = ${JSON.stringify(modified("llms.md"))};`,
    "",
  ].join("\n");
}

/** The generated module without its dates, for --check (a fresh checkout's file times differ from the build's). */
const withoutDates = text => text.replace(/^export const LLMS_TXT_MODIFIED.*$/gm, "");

const args = new Set(process.argv.slice(2));
const content = llmsModule();
if (!existsSync(join(llmsDir, "llms.md"))) console.warn("build:llms: store/llms/llms.md is missing, so /llms.txt and /llms-full.txt answer 404");
if (args.has("--check")) {
  const current = existsSync(output) ? readFileSync(output, "utf8") : "";
  if (withoutDates(current) !== withoutDates(content)) {
    console.error("build:llms: lib/agent/generated/llms.ts is out of date with store/llms/llms.md. Run `pnpm build:llms`.");
    process.exit(1);
  }
} else {
  const current = existsSync(output) ? readFileSync(output, "utf8") : null;
  if (current !== content) {
    mkdirSync(dirname(output), { recursive: true });
    const temporary = `${output}.${process.pid}.tmp`;
    writeFileSync(temporary, content);
    renameSync(temporary, output);
    if (!args.has("--quiet")) console.log("build:llms: wrote lib/agent/generated/llms.ts");
  }
}
